name: CI (Self-Hosted Analytics)

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Який файл запустити"
        default: "all"

jobs:
  run-local:
    runs-on: self-hosted # Вказуємо твій локальний ранер

    strategy:
      fail-fast: false
      matrix:
        module: [01_quality_check, 02_research, 03_viz]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        env:
          RUNNER_TOOL_CACHE: /Users/mac/open-data-ai-analytics-Orza/actions-runner/_work/_tool
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas jupyter nbconvert matplotlib

      - name: Copy local big dataset
        run: |
            echo "1. Поточна робоча папка ранера:"
            pwd
            
            echo "2. Чи бачить ранер оригінальний файл на Mac?"
            ls -lh /Users/mac/open-data-ai-analytics-Orza/data/reestrtz28.02.2026.csv || echo "ОРИГІНАЛЬНИЙ ФАЙЛ НЕ ЗНАЙДЕНО!"
            
            echo "3. Створюю папку і копіюю..."
            mkdir -p data
            cp /Users/mac/open-data-ai-analytics-Orza/data/reestrtz28.02.2026.csv data/
            
            echo "4. Що тепер лежить у папці data всередині ранера?"
            ls -lh data/

      - name: Run analysis files
        run: |
          mkdir -p artifacts/${{ matrix.module }}
          echo "Запускаємо ${{ matrix.module }}..."
          
          if [ -f "notebooks/${{ matrix.module }}.ipynb" ]; then
            jupyter nbconvert --to notebook --execute "notebooks/${{ matrix.module }}.ipynb" --output-dir "artifacts/${{ matrix.module }}"
          elif [ -f "notebooks/${{ matrix.module }}.ipynb.py" ]; then
            python "notebooks/${{ matrix.module }}.ipynb.py" > "artifacts/${{ matrix.module }}/run.log" 2>&1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.module }}-local
          path: artifacts/${{ matrix.module }}